// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MutualFundStats.Data;

#nullable disable

namespace MutualFundStats.Migrations
{
    [DbContext(typeof(MutualFundDataContext))]
    [Migration("20241008082743_AddMutualFundsTableToDb")]
    partial class AddMutualFundsTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MutualFundStats.Data.Scheme", b =>
                {
                    b.Property<int>("SchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchemeId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchemeId");

                    b.ToTable("Schemes");
                });

            modelBuilder.Entity("MutualFundStats.Models.MutualFundData", b =>
                {
                    b.Property<int>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatId"));

                    b.Property<decimal>("AverageNetAssetsUnderManagement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FundsMobilized")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Month")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NetAssetsUnderManagement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetInflowOutflow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumberOfFolios")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSchemes")
                        .HasColumnType("int");

                    b.Property<decimal>("RepurchaseRedemption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SchemeId")
                        .HasColumnType("int");

                    b.Property<int>("Scheme_Id")
                        .HasColumnType("int");

                    b.HasKey("StatId");

                    b.HasIndex("SchemeId");

                    b.ToTable("MutualFundDatas");
                });

            modelBuilder.Entity("MutualFundStats.Models.MutualFundData", b =>
                {
                    b.HasOne("MutualFundStats.Data.Scheme", "Scheme")
                        .WithMany("MutualFundDatas")
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Scheme");
                });

            modelBuilder.Entity("MutualFundStats.Data.Scheme", b =>
                {
                    b.Navigation("MutualFundDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
